// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.WorkItems.DrivenInfrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.WorkItems.DrivenInfrastructure.Migrations;

[DbContext(typeof(WorkItemsDbContext))]
[Migration("20260519161604_AddFieldReadModelWorkItemTypes")]
partial class AddFieldReadModelWorkItemTypes
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("workitem")
            .HasAnnotation("ProductVersion", "10.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("BuildingBlocks.DrivenInfrastructure.Inbox.InboxMessage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("ReceivedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("InboxMessages", "workitem");
            });

        modelBuilder.Entity("BuildingBlocks.DrivenInfrastructure.Outbox.OutboxMessage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Error")
                    .HasColumnType("text");

                b.Property<DateTime>("OccurredAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("ProcessedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("OutboxMessages", "workitem");
            });

        modelBuilder.Entity("FieldReadModelWorkItemType", b =>
            {
                b.Property<Guid>("field_read_model_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("work_item_type_id")
                    .HasColumnType("uuid");

                b.HasKey("field_read_model_id", "work_item_type_id");

                b.HasIndex("work_item_type_id");

                b.ToTable("field_read_model_work_item_types", "workitem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.ActivityLog", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("FieldName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("field_name");

                b.Property<string>("NewValue")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("new_value");

                b.Property<string>("OldValue")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("old_value");

                b.Property<Guid>("user_read_model_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("work_item_id")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("user_read_model_id");

                b.HasIndex("work_item_id");

                b.ToTable("activity_logs", "workitem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.Attachment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("file_name");

                b.Property<string>("FileUrl")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("file_url");

                b.Property<DateTime>("UploadedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("uploaded_at");

                b.Property<Guid?>("comment_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("user_read_model_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("work_item_id")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("comment_id");

                b.HasIndex("user_read_model_id");

                b.HasIndex("work_item_id");

                b.ToTable("attachments", "workitem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.Field.FieldReadModel", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<bool>("IsOptional")
                    .HasColumnType("boolean")
                    .HasColumnName("is_optional");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("name");

                b.Property<Guid>("field_type_read_model_id")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("field_type_read_model_id");

                b.ToTable("field_read_models", "workitem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.Field.FieldTypeReadModel", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("name");

                b.HasKey("Id");

                b.ToTable("field_type_read_models", "workitem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.Field.FieldValue", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("value");

                b.Property<Guid>("field_read_model_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("work_item_id")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("work_item_id");

                b.HasIndex("field_read_model_id", "work_item_id")
                    .IsUnique();

                b.ToTable("field_values", "workitem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.ProjectReadModel", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Abbreviation")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("abbreviation");

                b.HasKey("Id");

                b.ToTable("project_read_models", "workitem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.Properties.WorkItemStatus", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("name");

                b.HasKey("Id");

                b.ToTable("work_item_statuses", "workitem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.Properties.WorkItemType", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("name");

                b.HasKey("Id");

                b.ToTable("work_item_types", "workitem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.UserReadModel", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("first_name");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("last_name");

                b.HasKey("Id");

                b.ToTable("user_read_models", "workitem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.WorkItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("Code")
                    .HasColumnType("integer")
                    .HasColumnName("code");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("description");

                b.Property<decimal>("Estimation")
                    .ValueGeneratedOnAdd()
                    .HasPrecision(10, 2)
                    .HasColumnType("numeric(10,2)")
                    .HasDefaultValue(0m)
                    .HasColumnName("estimation");

                b.Property<DateTime>("LimitDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("limit_date");

                b.Property<Guid?>("ParentId")
                    .HasColumnType("uuid")
                    .HasColumnName("parent_id");

                b.Property<int>("Progress")
                    .HasColumnType("integer")
                    .HasColumnName("progress");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("character varying(250)")
                    .HasColumnName("title");

                b.Property<Guid?>("assignee_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("project_read_model_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("status_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("type_id")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("ParentId");

                b.HasIndex("assignee_id");

                b.HasIndex("project_read_model_id");

                b.HasIndex("status_id");

                b.HasIndex("type_id");

                b.ToTable("work_items", "workitem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.WorkItemComment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("content");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<Guid>("user_read_model_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("work_item_id")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("user_read_model_id");

                b.HasIndex("work_item_id");

                b.ToTable("work_item_comments", "workitem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.WorkLog", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Comment")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("comment");

                b.Property<DateTime>("Date")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("date");

                b.Property<decimal>("Hours")
                    .HasPrecision(5, 2)
                    .HasColumnType("numeric(5,2)")
                    .HasColumnName("hours");

                b.Property<Guid>("user_read_model_id")
                    .HasColumnType("uuid");

                b.Property<Guid>("work_item_id")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("user_read_model_id");

                b.HasIndex("work_item_id");

                b.ToTable("work_logs", "workitem");
            });

        modelBuilder.Entity("FieldReadModelWorkItemType", b =>
            {
                b.HasOne("Modules.WorkItems.Domain.Entities.Field.FieldReadModel", null)
                    .WithMany()
                    .HasForeignKey("field_read_model_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Modules.WorkItems.Domain.Entities.Properties.WorkItemType", null)
                    .WithMany()
                    .HasForeignKey("work_item_type_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.ActivityLog", b =>
            {
                b.HasOne("Modules.WorkItems.Domain.Entities.UserReadModel", "UserReadModel")
                    .WithMany()
                    .HasForeignKey("user_read_model_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Modules.WorkItems.Domain.Entities.WorkItem", "WorkItem")
                    .WithMany()
                    .HasForeignKey("work_item_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("UserReadModel");

                b.Navigation("WorkItem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.Attachment", b =>
            {
                b.HasOne("Modules.WorkItems.Domain.Entities.WorkItemComment", "Comment")
                    .WithMany()
                    .HasForeignKey("comment_id")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("Modules.WorkItems.Domain.Entities.UserReadModel", "User")
                    .WithMany()
                    .HasForeignKey("user_read_model_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Modules.WorkItems.Domain.Entities.WorkItem", "WorkItem")
                    .WithMany()
                    .HasForeignKey("work_item_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Comment");

                b.Navigation("User");

                b.Navigation("WorkItem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.Field.FieldReadModel", b =>
            {
                b.HasOne("Modules.WorkItems.Domain.Entities.Field.FieldTypeReadModel", "FieldType")
                    .WithMany()
                    .HasForeignKey("field_type_read_model_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("FieldType");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.Field.FieldValue", b =>
            {
                b.HasOne("Modules.WorkItems.Domain.Entities.Field.FieldReadModel", "Field")
                    .WithMany()
                    .HasForeignKey("field_read_model_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Modules.WorkItems.Domain.Entities.WorkItem", "WorkItem")
                    .WithMany()
                    .HasForeignKey("work_item_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Field");

                b.Navigation("WorkItem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.WorkItem", b =>
            {
                b.HasOne("Modules.WorkItems.Domain.Entities.WorkItem", null)
                    .WithMany()
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("Modules.WorkItems.Domain.Entities.UserReadModel", "Asignee")
                    .WithMany()
                    .HasForeignKey("assignee_id")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("Modules.WorkItems.Domain.Entities.ProjectReadModel", "Project")
                    .WithMany()
                    .HasForeignKey("project_read_model_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Modules.WorkItems.Domain.Entities.Properties.WorkItemStatus", "Status")
                    .WithMany()
                    .HasForeignKey("status_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Modules.WorkItems.Domain.Entities.Properties.WorkItemType", "Type")
                    .WithMany()
                    .HasForeignKey("type_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Asignee");

                b.Navigation("Project");

                b.Navigation("Status");

                b.Navigation("Type");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.WorkItemComment", b =>
            {
                b.HasOne("Modules.WorkItems.Domain.Entities.UserReadModel", "User")
                    .WithMany()
                    .HasForeignKey("user_read_model_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Modules.WorkItems.Domain.Entities.WorkItem", "WorkItem")
                    .WithMany()
                    .HasForeignKey("work_item_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");

                b.Navigation("WorkItem");
            });

        modelBuilder.Entity("Modules.WorkItems.Domain.Entities.WorkLog", b =>
            {
                b.HasOne("Modules.WorkItems.Domain.Entities.UserReadModel", "User")
                    .WithMany()
                    .HasForeignKey("user_read_model_id")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Modules.WorkItems.Domain.Entities.WorkItem", "WorkItem")
                    .WithMany()
                    .HasForeignKey("work_item_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");

                b.Navigation("WorkItem");
            });
#pragma warning restore 612, 618
    }
}
