// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Projects.DrivenInfrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Projects.DrivenInfrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProjectsDbContext))]
    [Migration("20260507213224_AddProjectInvitations")]
    partial class AddProjectInvitations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("project")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.DrivenInfrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InboxMessages", "project");
                });

            modelBuilder.Entity("BuildingBlocks.DrivenInfrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Field.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_optional");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("field_type_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("field_type_id");

                    b.ToTable("fields", "project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Field.FieldType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("field_types", "project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Field.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("field_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("field_id");

                    b.ToTable("options", "project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Field.ProjectField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Default")
                        .HasColumnType("boolean")
                        .HasColumnName("default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("Optional")
                        .HasColumnType("boolean")
                        .HasColumnName("optional");

                    b.Property<Guid>("field_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("project_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("field_id");

                    b.HasIndex("project_id");

                    b.ToTable("project_fields", "project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Invitation.ProjectInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at");

                    b.Property<Guid>("InviteeId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitee_id");

                    b.Property<int>("InviteeType")
                        .HasColumnType("integer")
                        .HasColumnName("invitee_type");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_role_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("ProjectId", "InviteeId")
                        .IsUnique();

                    b.ToTable("project_invitations", "project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Member.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<int>("MemberType")
                        .HasColumnType("integer")
                        .HasColumnName("member_type");

                    b.Property<Guid>("project_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("project_role_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("project_role_id");

                    b.HasIndex("project_id", "MemberId")
                        .IsUnique();

                    b.ToTable("project_members", "project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Owner.OrganizationReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("organizations_read_models", "project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Owner.UserReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users_read_models", "project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("abbreviation");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer")
                        .HasColumnName("owner_type");

                    b.Property<int>("Privacy")
                        .HasColumnType("integer")
                        .HasColumnName("privacy");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Abbreviation")
                        .IsUnique();

                    b.HasIndex("OwnerId", "OwnerType");

                    b.ToTable("projects", "project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Role.ProjectPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("permission_group_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("permission_group_id");

                    b.ToTable("project_permissions", "project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Role.ProjectPermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("project_permission_groups", "project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Role.ProjectRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOwnerRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_owner_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("project_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("project_id", "Name")
                        .IsUnique();

                    b.ToTable("project_roles", "project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Role.ProjectRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("permission_level");

                    b.Property<Guid>("project_permission_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("project_role_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("project_permission_id");

                    b.HasIndex("project_role_id", "project_permission_id")
                        .IsUnique();

                    b.ToTable("project_role_permissions", "project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Field.Field", b =>
                {
                    b.HasOne("Modules.Projects.Domain.Entities.Field.FieldType", "FieldType")
                        .WithMany()
                        .HasForeignKey("field_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FieldType");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Field.Option", b =>
                {
                    b.HasOne("Modules.Projects.Domain.Entities.Field.Field", "Field")
                        .WithMany()
                        .HasForeignKey("field_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Field.ProjectField", b =>
                {
                    b.HasOne("Modules.Projects.Domain.Entities.Field.Field", "Field")
                        .WithMany()
                        .HasForeignKey("field_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modules.Projects.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Invitation.ProjectInvitation", b =>
                {
                    b.HasOne("Modules.Projects.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Projects.Domain.Entities.Role.ProjectRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Member.ProjectMember", b =>
                {
                    b.HasOne("Modules.Projects.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Projects.Domain.Entities.Role.ProjectRole", "Role")
                        .WithMany()
                        .HasForeignKey("project_role_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Role.ProjectPermission", b =>
                {
                    b.HasOne("Modules.Projects.Domain.Entities.Role.ProjectPermissionGroup", "PermissionGroup")
                        .WithMany()
                        .HasForeignKey("permission_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Role.ProjectRole", b =>
                {
                    b.HasOne("Modules.Projects.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Modules.Projects.Domain.Entities.Role.ProjectRolePermission", b =>
                {
                    b.HasOne("Modules.Projects.Domain.Entities.Role.ProjectPermission", "Permission")
                        .WithMany()
                        .HasForeignKey("project_permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Projects.Domain.Entities.Role.ProjectRole", "Role")
                        .WithMany()
                        .HasForeignKey("project_role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
