// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Agents.DrivenInfrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Agents.DrivenInfrastructure.Migrations
{
    [DbContext(typeof(AgentsDbContext))]
    [Migration("20260608142652_AddExecutionMode")]
    partial class AddExecutionMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("agent")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.DrivenInfrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InboxMessages", "agent");
                });

            modelBuilder.Entity("BuildingBlocks.DrivenInfrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid>("model_config_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("model_config_id");

                    b.ToTable("agents", "agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.AgentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("agent_templates", "agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.AgentTriggers.AgentEventTrigger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_prompt");

                    b.Property<Guid>("agent_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("agent_id");

                    b.ToTable("agent_event_triggers", "agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.AgentTriggers.AgentTimeTrigger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<Guid>("agent_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("agent_id");

                    b.ToTable("agent_time_triggers", "agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.Execution.AgentExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("agent_executions", "agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.Execution.AgentExecutionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<string>("ToolCalls")
                        .HasColumnType("text")
                        .HasColumnName("tool_calls");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("agent_execution_messages", "agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.Execution.AgentExecutionPendingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.ToTable("agent_execution_pending_events", "agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.Model.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Cost")
                        .HasColumnType("double precision")
                        .HasColumnName("cost");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("provider_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("provider_id");

                    b.ToTable("models", "agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.Model.ModelConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_tokens");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.Property<Guid>("model_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("model_id");

                    b.ToTable("model_configs", "agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.Model.ModelProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.ToTable("model_providers", "agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.ProjectReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("project_read_models", "agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.Agent", b =>
                {
                    b.HasOne("Modules.Agents.Domain.Entities.ProjectReadModel", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Agents.Domain.Entities.Model.ModelConfig", "ModelConfig")
                        .WithMany()
                        .HasForeignKey("model_config_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelConfig");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.AgentTriggers.AgentEventTrigger", b =>
                {
                    b.HasOne("Modules.Agents.Domain.Entities.Agent", "Agent")
                        .WithMany("EventTriggers")
                        .HasForeignKey("agent_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.AgentTriggers.AgentTimeTrigger", b =>
                {
                    b.HasOne("Modules.Agents.Domain.Entities.Agent", "Agent")
                        .WithMany("TimeTriggers")
                        .HasForeignKey("agent_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.Execution.AgentExecution", b =>
                {
                    b.HasOne("Modules.Agents.Domain.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.Execution.AgentExecutionPendingEvent", b =>
                {
                    b.HasOne("Modules.Agents.Domain.Entities.Execution.AgentExecution", null)
                        .WithMany("PendingEvents")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.Model.Model", b =>
                {
                    b.HasOne("Modules.Agents.Domain.Entities.Model.ModelProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("provider_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.Model.ModelConfig", b =>
                {
                    b.HasOne("Modules.Agents.Domain.Entities.Model.Model", "Model")
                        .WithMany()
                        .HasForeignKey("model_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.Agent", b =>
                {
                    b.Navigation("EventTriggers");

                    b.Navigation("TimeTriggers");
                });

            modelBuilder.Entity("Modules.Agents.Domain.Entities.Execution.AgentExecution", b =>
                {
                    b.Navigation("PendingEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
