type: object
properties:
  requestId:
    type: string
    format: uuid
    example: 'asd123asd-1234-5678-90ab-cdef12345678'
  timestamp:
    type: string
    format: date-time
    example: '2024-06-01T12:00:00Z'

required:
  - requestId
  - timestamp
